package tokenizer;

public enum TokenType {
    // Add the tokens from token table here
    KW_POKEMON, KW_INT, KW_STRING, KW_BOOLEAN,
    KEYWORD, IDENTIFIER,
    INT_LITERAL, STRING_LITERAL,
    OP_ASSIGN, OP_EQUALS, OP_LESS_THAN, OP_GREATER_THAN, OP_LESS_THAN_EQUALS, OP_GREATER_THAN_EQUALS,
    OP_PLUS_ASSIGN, OP_MINUS_ASSIGN, OP_PLUS, OP_MINUS, OP_MULTIPLY, OP_DIVIDE, OP_AND, OP_OR, OP_NOT, OP_NOTEQUAL,
    LPAREN, RPAREN, LBRACE, RBRACE,
    SEMICOLON, COMMA, DOT, WHITESPACE,
    EOF
}
