package tokenizer;

public enum TokenType {
    // Add the tokens from token table here
    KW_POKEMON, KW_INT, KW_STRING, KW_BOOLEAN, KW_FOR, KW_IF, KW_WHILE, KW_PRINT, KW_RETURN,
    KW_FUNCTION, KW_VOID, KW_ELSEIF, KW_ELSE, KW_SHOW, KW_SPELLDATABASE,
    KW_MOVE1, KW_MOVE2, KW_MOVE3, KW_MOVE4,
    KW_CONTINUE, KW_BREAK,
    KEYWORD, OP_TRUE, OP_FALSE, IDENTIFIER,
    INT_LITERAL, STRING_LITERAL,
    OP_ASSIGN, OP_EQUALS, OP_LESS_THAN, OP_GREATER_THAN, OP_LESS_THAN_EQUALS, OP_GREATER_THAN_EQUALS,
    OP_PLUS_ASSIGN, OP_MINUS_ASSIGN, OP_PLUS, OP_MINUS, OP_MULTIPLY, OP_DIVIDE, OP_AND, OP_OR, OP_NOT, OP_NOTEQUAL,
    LPAREN, RPAREN, LBRACE, RBRACE,
    SEMICOLON, COMMA, DOT, WHITESPACE,
    EOF
}
